### ISSUE TITLE
Bioconductor version not available, github install incompatible with bioconductor-based RCM

### ISSUE THREAD

**Issue by FMKerckhof** [CenterForStatistics-UGent/combi#1]
Trying to install `combi` using `BiocManager::install("combi")` results in `package ‘combi’ is not available (for R version 3.6.2)` warning (BiocManager 1.30.10, Bioconductor version 3.9). Installing using `devtools::install_github("CenterForStatistics-UGent/combi")` throws errors if RCM 1.0.0 is installed from Bioconductor (`Error: object ‘checkAlias’ is not exported by 'namespace:RCM'`) but not if RCM 1.2.1 was installed using `devtools`

**Comment by sthawinke** [comment]
@JoFAM could you help out?

**Comment by sthawinke** [comment]
The BioConductor version has been hidden for now (submission soon follows), and a requirement for RCM >= 1.1.2 has been added. I am closing the issue now
