### ISSUE TITLE
BioConductor submission

### ISSUE THREAD

**Issue by sthawinke** [CenterForStatistics-UGent/combi#2]
@JoFAM I reviewed the code one more time, for me this is ready to submit in the following weeks

**Comment by sthawinke** [comment]
Hi @JoFAM would you have time to review this shortly? Otherwise no worries, but it is about time I submitted this, I will hear from the reviewers then. Thanks!

**Comment by JoFAM** [comment]
@sthawinke sorry man, work overload prevented me from going through it. Keep me updated about the comments of the reviewers, I'll help fixing stuff whenever I can.
