### ISSUE TITLE
error while executing combi function

### ISSUE THREAD

**Issue by jgiemza** [CenterForStatistics-UGent/combi#3]
Hello,

This is the what I got while running combi fuction on my data:

Iteration:  0  ||F(x0)||:  2.194605e-10 
Iteration:  0  ||F(x0)||:  4.316424e-12 
Error in meanVarTrend(c(CompMat), libSizes = libSizes) : 
  argument "CompMat" is missing, with no default
Error in meanVarTrend(c(CompMat), libSizes = libSizes) : 
  argument "CompMat" is missing, with no default
Error in meanVarTrend(c(CompMat), libSizes = libSizes) : 
  argument "CompMat" is missing, with no default
Error in meanVarTrend(c(CompMat), libSizes = libSizes) : 
  argument "CompMat" is missing, with no default
Error in meanVarTrend(c(CompMat), libSizes = libSizes) : 
  argument "CompMat" is missing, with no default
Error in meanVarTrend(c(CompMat), libSizes = libSizes) : 
  argument "CompMat" is missing, with no default
Error in BBsolve(par = c(paramEsts[[i]][m, ], lambdasParams[[i]][seqM(m,  : 
  object 'ans.best' not found

Thanks in advance for help

**Comment by sthawinke** [comment]
My apologies for the bug and late reply, this occurs when combining non-compositional data with quasi likelihood. This is currently not implemented, and very likely will not be in the near future. The method should throw an informative error now.
